# Generated by Django 4.2.1 on 2025-10-30 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0012_add_commission_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_type', models.CharField(choices=[('lead', 'Lead'), ('customer', 'Customer'), ('agent', 'Agent'), ('walkin', 'Walk-in'), ('booking_contact', 'Booking Contact'), ('other', 'Other')], default='other', max_length=30)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization_id', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['phone'], name='promotion_c_phone_31fec4_idx'), models.Index(fields=['organization_id'], name='promotion_c_organiz_9a318e_idx')],
            },
        ),
    ]
