"""Auto migration: add status field and make organization_id nullable

Generated by assistant to align model and DB for tests.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion_center", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotioncontact",
            name="organization_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotioncontact",
            name="status",
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16),
            preserve_default=False,
        ),
    ]
