"""Add notes field to PromotionContact

Generated by assistant to add a notes TextField for admin/marketing comments.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion_center", "0002_add_status_and_nullable_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotioncontact",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
