# Generated by Django 4.2.1 on 2025-07-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='agreement_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='UserFiles',
        ),
    ]
