# Generated by Django 4.2.1 on 2025-10-29 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0067_bookingcallremark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0011_alter_rule_created_by_alter_rule_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cnic_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lead_source', models.CharField(choices=[('walk-in', 'walk-in'), ('call', 'call'), ('whatsapp', 'whatsapp'), ('facebook', 'facebook'), ('referral', 'referral')], default='walk-in', max_length=30)),
                ('lead_status', models.CharField(choices=[('new', 'new'), ('followup', 'followup'), ('confirmed', 'confirmed'), ('lost', 'lost')], default='new', max_length=30)),
                ('interested_in', models.CharField(blank=True, choices=[('ticket', 'ticket'), ('umrah', 'umrah'), ('visa', 'visa'), ('transport', 'transport'), ('hotel', 'hotel')], max_length=30, null=True)),
                ('interested_travel_date', models.DateField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('loan_promise_date', models.DateField(blank=True, null=True)),
                ('loan_status', models.CharField(choices=[('pending', 'pending'), ('cleared', 'cleared'), ('overdue', 'overdue')], default='pending', max_length=20)),
                ('last_contacted_date', models.DateField(blank=True, null=True)),
                ('conversion_status', models.CharField(choices=[('not_converted', 'not_converted'), ('converted_to_booking', 'converted_to_booking'), ('lost', 'lost')], default='not_converted', max_length=30)),
                ('pex_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='booking.booking')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='organization.branch')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LoanCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promised_clear_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('cleared', 'cleared'), ('overdue', 'overdue')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_commitments', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('contacted_via', models.CharField(choices=[('call', 'call'), ('whatsapp', 'whatsapp'), ('in-person', 'in-person')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_result', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('lost', 'lost')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead')),
            ],
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['passport_number'], name='leads_lead_passpor_da7d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['contact_number'], name='leads_lead_contact_85af59_idx'),
        ),
    ]
