# Generated by Django 4.2.1 on 2025-07-15 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/agency_logos')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='organization.branch')),
                ('user', models.ManyToManyField(related_name='agencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
