# Generated by Django 4.2.1 on 2025-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_agencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/agency_logos'),
        ),
    ]
