# Generated by Django 4.2.1 on 2025-10-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_agency_credit_and_assign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationlink',
            options={'managed': True},
        ),
    ]
