# Generated by Django 4.2.1 on 2025-10-28 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0008_alter_organizationlink_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_status', models.CharField(default='active', max_length=50)),
                ('relation_history', models.JSONField(default=list)),
                ('working_with_companies', models.JSONField(default=list)),
                ('performance_summary', models.JSONField(default=dict)),
                ('recent_communication', models.JSONField(default=list)),
                ('conflict_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.agency')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agency_profiles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_agency_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
