# Generated by Django 4.2.1 on 2025-10-28 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0009_agencyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('policy', 'Policy'), ('commission_rule', 'Commission Rule')], max_length=100)),
                ('pages_to_display', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], default='en', max_length=10)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
