# Generated by Django 4.2.1 on 2025-10-28 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_remove_hotels_google_drive_link'),
        ('organization', '0010_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WalkInBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('booking_type', models.CharField(default='walk_in', max_length=30)),
                ('customer', models.JSONField(default=dict)),
                ('room_details', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cleaning_pending', 'Cleaning Pending'), ('available', 'Available')], default='checked_in', max_length=30)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.hotels')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'walkin_bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
