# Generated by Django 4.2.1 on 2025-10-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='internal_notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
