# Generated by Django 5.2.7 on 2025-10-23 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUmrahPackageHotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('sharing_type', models.CharField(blank=True, max_length=20, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('number_of_nights', models.IntegerField(default=0)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUmrahPackageTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUmrahPackageTransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUmrahZiaratDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('min_pex', models.IntegerField(default=0)),
                ('per_pex', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OnlyVisaPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adault_price', models.FloatField(default=0)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('min_days', models.CharField(max_length=50)),
                ('max_days', models.CharField(max_length=50)),
                ('airpot_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiyalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
                ('is_visa_pkr', models.BooleanField(default=False)),
                ('is_hotel_pkr', models.BooleanField(default=False)),
                ('is_transport_pkr', models.BooleanField(default=False)),
                ('is_ziarat_pkr', models.BooleanField(default=False)),
                ('is_food_pkr', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SetVisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shirka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransportSectorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='type1', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.IntegerField(blank=True, null=True)),
                ('adault_price', models.FloatField(default=0)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('is_visa', models.BooleanField(default=False)),
                ('only_transport_charge', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rules', models.TextField(blank=True, null=True)),
                ('child_visa_price', models.FloatField(default=0)),
                ('infant_visa_price', models.FloatField(default=0)),
                ('adault_visa_price', models.FloatField(default=0)),
                ('food_price', models.FloatField(default=0)),
                ('makkah_ziyarat_price', models.FloatField(default=0)),
                ('madinah_ziyarat_price', models.FloatField(default=0)),
                ('transport_price', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_quaint_active', models.BooleanField(default=True)),
                ('is_sharing_active', models.BooleanField(default=True)),
                ('is_quad_active', models.BooleanField(default=True)),
                ('is_triple_active', models.BooleanField(default=True)),
                ('is_double_active', models.BooleanField(default=True)),
                ('adault_service_charge', models.FloatField(default=0)),
                ('child_service_charge', models.FloatField(default=0)),
                ('infant_service_charge', models.FloatField(default=0)),
                ('is_service_charge_active', models.BooleanField(default=False)),
                ('adault_partial_payment', models.FloatField(default=0)),
                ('child_partial_payment', models.FloatField(default=0)),
                ('infant_partial_payment', models.FloatField(default=0)),
                ('is_partial_payment_active', models.BooleanField(default=False)),
                ('filght_min_adault_age', models.IntegerField(default=0)),
                ('filght_max_adault_age', models.IntegerField(default=0)),
                ('max_chilld_allowed', models.IntegerField(default=0)),
                ('max_infant_allowed', models.IntegerField(default=0)),
                ('total_seats', models.BigIntegerField(blank=True, default=0, null=True)),
                ('left_seats', models.BigIntegerField(blank=True, default=0, null=True)),
                ('booked_seats', models.BigIntegerField(blank=True, default=0, null=True)),
                ('confirmed_seats', models.BigIntegerField(blank=True, default=0, null=True)),
                ('inventory_owner_organization_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackageDiscountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adault_from', models.IntegerField(default=0)),
                ('adault_to', models.IntegerField(default=0)),
                ('max_discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackageHotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('number_of_nights', models.IntegerField(default=0)),
                ('quaint_bed_price', models.FloatField(default=0)),
                ('sharing_bed_price', models.FloatField(default=0)),
                ('quad_bed_price', models.FloatField(default=0)),
                ('triple_bed_price', models.FloatField(default=0)),
                ('double_bed_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackageTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackageTransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.IntegerField(blank=True, null=True)),
                ('transport_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UmrahVisaPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('adault_price', models.FloatField(default=0)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('maximum_nights', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UmrahVisaPriceTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('person_from', models.IntegerField(default=0)),
                ('person_to', models.IntegerField(default=0)),
                ('adault_price', models.FloatField(default=0)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('is_transport', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UmrahVisaPriceTwoHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ZiaratPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziarat_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('min_pex', models.FloatField(default=0)),
                ('max_pex', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/airlines_logos/')),
                ('is_umrah_seat', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BookingExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umrah_expiry_time', models.IntegerField(default=0)),
                ('ticket_expiry_time', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_expiries', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUmrahPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_adaults', models.IntegerField(default=0)),
                ('total_children', models.IntegerField(default=0)),
                ('total_infants', models.IntegerField(default=0)),
                ('child_visa_price', models.FloatField(default=0)),
                ('infant_visa_price', models.FloatField(default=0)),
                ('adault_visa_price', models.FloatField(default=0)),
                ('long_term_stay', models.BooleanField(default=False)),
                ('is_full_transport', models.BooleanField(default=False)),
                ('is_one_side_transport', models.BooleanField(default=False)),
                ('only_visa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_umrah_packages', to='organization.agency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_umrah_packages', to='organization.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_umrah_packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUmrahFoodDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_details', to='packages.customumrahpackage')),
            ],
        ),
    ]
