# Generated by Django 5.2.7 on 2025-10-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_initial'),
        ('organization', '0001_initial'),
        ('packages', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customumrahpackagehoteldetails',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.hotels'),
        ),
        migrations.AddField(
            model_name='customumrahpackagehoteldetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='packages.customumrahpackage'),
        ),
        migrations.AddField(
            model_name='customumrahpackageticketdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_details', to='packages.customumrahpackage'),
        ),
        migrations.AddField(
            model_name='customumrahpackageticketdetails',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='customumrahpackagetransportdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='packages.customumrahpackage'),
        ),
        migrations.AddField(
            model_name='customumrahziaratdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziarat_details', to='packages.customumrahpackage'),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_prices', to='packages.city'),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_prices', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='customumrahfooddetails',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.foodprice'),
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='only_visa_prices', to='packages.city'),
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='only_visa_prices', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='riyalrate',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='setvisatype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='shirka',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirkas', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='transportsectorprice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_sectors', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umrah_packages', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='umrahpackagediscountdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_details', to='packages.umrahpackage'),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.hotels'),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='packages.umrahpackage'),
        ),
        migrations.AddField(
            model_name='umrahpackageticketdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_details', to='packages.umrahpackage'),
        ),
        migrations.AddField(
            model_name='umrahpackageticketdetails',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='umrahpackagetransportdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='packages.umrahpackage'),
        ),
        migrations.AddField(
            model_name='umrahpackagetransportdetails',
            name='transport_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.transportsectorprice'),
        ),
        migrations.AddField(
            model_name='umrahvisaprice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umrah_visa_prices', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='umrahvisapricetwo',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umrah_visa_prices_two', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='umrahvisapricetwo',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, related_name='umrah_visa_prices_two', to='booking.vehicletype'),
        ),
        migrations.AddField(
            model_name='umrahvisapricetwohotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.hotels'),
        ),
        migrations.AddField(
            model_name='umrahvisapricetwohotel',
            name='umrah_visa_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='packages.umrahvisapricetwo'),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ziarat_prices', to='packages.city'),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziarat_prices', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='customumrahziaratdetails',
            name='ziarat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.ziaratprice'),
        ),
    ]
