# Generated by Django 4.2.1 on 2025-10-29 21:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=150)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('cnic', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('office_walkin', 'office_walkin'), ('call', 'call'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('website', 'website'), ('whatsapp', 'whatsapp'), ('other', 'other')], default='office_walkin', max_length=30)),
                ('lead_status', models.CharField(choices=[('pending', 'pending'), ('waiting_response', 'waiting_response'), ('converted', 'converted'), ('lost', 'lost')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadPaymentPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('customer_promise', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('cleared', 'cleared'), ('overdue', 'overdue')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_promises', to='area_leads.arealead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_followup_date', models.DateField()),
                ('next_followup_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('followup_status', models.CharField(choices=[('waiting_response', 'waiting_response'), ('contacted', 'contacted'), ('lost', 'lost')], default='waiting_response', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='area_leads.arealead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('call', 'call'), ('whatsapp', 'whatsapp'), ('meeting', 'meeting'), ('note', 'note')], max_length=30)),
                ('summary', models.TextField()),
                ('recorded_by', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='area_leads.arealead')),
            ],
        ),
    ]
