# Generated by Django 4.2.1 on 2025-10-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealead',
            name='passport_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='arealead',
            constraint=models.UniqueConstraint(fields=('branch_id', 'passport_number'), name='unique_branch_passport'),
        ),
    ]
