# Generated by Django 4.2.1 on 2025-07-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahVisaPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('adault_price', models.FloatField(default=0)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('maximum_nights', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umrah_visa_prices', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TransportSectorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('adault_price', models.FloatField(default=0)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('is_visa', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_sectors', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Shirka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirkas', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RiyalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BookingExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umrah_expiry_time', models.IntegerField(default=0)),
                ('ticket_expiry_time', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_expiries', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/airlines_logos/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='organization.organization')),
            ],
        ),
    ]
