# Generated by Django 4.2.1 on 2025-07-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riyalrate',
            name='is_hotel_pkr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riyalrate',
            name='is_transport_pkr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riyalrate',
            name='is_visa_pkr',
            field=models.BooleanField(default=False),
        ),
    ]
