# Generated by Django 4.2.1 on 2025-07-09 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('tickets', '0002_alter_hotels_city'),
        ('packages', '0002_riyalrate_is_hotel_pkr_riyalrate_is_transport_pkr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rules', models.TextField(blank=True, null=True)),
                ('total_seats', models.IntegerField(default=0)),
                ('visa_price', models.FloatField(default=0)),
                ('food_price', models.FloatField(default=0)),
                ('makkah_ziyarat_price', models.FloatField(default=0)),
                ('madinah_ziyarat_price', models.FloatField(default=0)),
                ('transport_price', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('adault_service_charge', models.FloatField(default=0)),
                ('child_service_charge', models.FloatField(default=0)),
                ('infant_service_charge', models.FloatField(default=0)),
                ('filght_min_adault_age', models.IntegerField(default=0)),
                ('filght_max_adault_age', models.IntegerField(default=0)),
                ('max_chilld_allowed', models.IntegerField(default=0)),
                ('max_infant_allowed', models.IntegerField(default=0)),
                ('discount_min_adault_age', models.IntegerField(default=0)),
                ('discount_max_adault_age', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umrah_packages', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackageTransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='packages.umrahpackage')),
                ('transport_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.transportsectorprice')),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackageTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_details', to='packages.umrahpackage')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackageHotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('number_of_nights', models.IntegerField(default=0)),
                ('sharing_bed_price', models.FloatField(default=0)),
                ('quad_bed_price', models.FloatField(default=0)),
                ('triple_bed_price', models.FloatField(default=0)),
                ('double_bed_price', models.FloatField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.hotels')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='packages.umrahpackage')),
            ],
        ),
    ]
