# Generated by Django 4.2.1 on 2025-07-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_agency'),
        ('packages', '0003_umrahpackage_umrahpackagetransportdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umrahpackage',
            name='discount_max_adault_age',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='discount_min_adault_age',
        ),
        migrations.RemoveField(
            model_name='umrahpackagehoteldetails',
            name='double_bed_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackagehoteldetails',
            name='quad_bed_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackagehoteldetails',
            name='sharing_bed_price',
        ),
        migrations.RemoveField(
            model_name='umrahpackagehoteldetails',
            name='triple_bed_price',
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='is_double_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='is_quad_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='is_quaint_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='is_sharing_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='is_triple_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='room_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='sharing_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UmrahPackageDiscountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adault_from', models.IntegerField(default=0)),
                ('adault_to', models.IntegerField(default=0)),
                ('max_discount', models.FloatField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_details', to='packages.umrahpackage')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUmrahPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_adaults', models.IntegerField(default=0)),
                ('total_children', models.IntegerField(default=0)),
                ('total_infants', models.IntegerField(default=0)),
                ('visa_price', models.FloatField(default=0)),
                ('long_term_stay', models.BooleanField(default=False)),
                ('is_full_transport', models.BooleanField(default=False)),
                ('is_one_side_transport', models.BooleanField(default=False)),
                ('only_visa', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_umrah_packages', to='organization.organization')),
            ],
        ),
        migrations.AlterField(
            model_name='umrahpackagehoteldetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='packages.customumrahpackage'),
        ),
        migrations.AlterField(
            model_name='umrahpackageticketdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_details', to='packages.customumrahpackage'),
        ),
        migrations.AlterField(
            model_name='umrahpackagetransportdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='packages.customumrahpackage'),
        ),
    ]
