# Generated by Django 4.2.1 on 2025-07-15 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_agency'),
        ('tickets', '0002_alter_hotels_city'),
        ('packages', '0004_remove_umrahpackage_discount_max_adault_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahVisaPriceTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('person_from', models.IntegerField(default=0)),
                ('person_to', models.IntegerField(default=0)),
                ('adault_price', models.FloatField(default=0)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('is_transport', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umrah_visa_prices_two', to='organization.organization')),
            ],
        ),
        migrations.RemoveField(
            model_name='umrahpackagehoteldetails',
            name='price',
        ),
        migrations.RemoveField(
            model_name='umrahpackagehoteldetails',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='umrahpackagehoteldetails',
            name='sharing_type',
        ),
        migrations.RemoveField(
            model_name='umrahpackagehoteldetails',
            name='special_request',
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='double_bed_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='quad_bed_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='quaint_bed_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='sharing_bed_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackagehoteldetails',
            name='triple_bed_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='umrahpackagehoteldetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='packages.umrahpackage'),
        ),
        migrations.AlterField(
            model_name='umrahpackageticketdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_details', to='packages.umrahpackage'),
        ),
        migrations.AlterField(
            model_name='umrahpackagetransportdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='packages.umrahpackage'),
        ),
        migrations.CreateModel(
            name='UmrahVisaPriceTwoHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.hotels')),
                ('umrah_visa_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='packages.umrahvisapricetwo')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUmrahPackageTransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='packages.customumrahpackage')),
                ('transport_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.transportsectorprice')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUmrahPackageTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_details', to='packages.customumrahpackage')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUmrahPackageHotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, max_length=20, null=True)),
                ('sharing_type', models.CharField(blank=True, max_length=20, null=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('number_of_nights', models.IntegerField(default=0)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.hotels')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='packages.customumrahpackage')),
            ],
        ),
    ]
