# Generated by Django 4.2.1 on 2025-07-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_agency'),
        ('packages', '0005_umrahvisapricetwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportsectorprice',
            name='only_transport_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportsectorprice',
            name='reference',
            field=models.CharField(default='type1', max_length=100),
        ),
        migrations.CreateModel(
            name='OnlyVisaPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adault_price', models.FloatField(default=0)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='only_visa_prices', to='organization.organization')),
            ],
        ),
    ]
