# Generated by Django 4.2.1 on 2025-07-16 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_agencycontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0006_transportsectorprice_only_transport_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customumrahpackage',
            name='visa_price',
        ),
        migrations.AddField(
            model_name='customumrahpackage',
            name='adault_visa_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customumrahpackage',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_umrah_packages', to='organization.agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customumrahpackage',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_umrah_packages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customumrahpackage',
            name='child_visa_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customumrahpackage',
            name='infant_visa_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='adault_partial_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_partial_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='infant_partial_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='is_partial_payment_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='is_service_charge_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SetVisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='organization.organization')),
            ],
        ),
    ]
