# Generated by Django 4.2.1 on 2025-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_remove_customumrahpackage_visa_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umrahpackage',
            name='visa_price',
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='adault_visa_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='child_visa_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='infant_visa_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='umrahpackagehoteldetails',
            name='check_in_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='umrahpackagehoteldetails',
            name='check_out_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
