# Generated by Django 4.2.1 on 2025-07-24 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_remove_umrahpackage_visa_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customumrahpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customumrahpackage',
            name='status',
            field=models.CharField(default="1", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customumrahpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='airpot_name',
            field=models.CharField(default='ok', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='max_days',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='min_days',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='type',
            field=models.CharField(default='type1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customumrahpackagehoteldetails',
            name='check_in_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customumrahpackagehoteldetails',
            name='check_out_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
