# Generated by Django 4.2.1 on 2025-07-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_agency_logo'),
        ('packages', '0009_customumrahpackage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riyalrate',
            name='is_food_pkr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riyalrate',
            name='is_ziarat_pkr',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ZiaratPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('price', models.FloatField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziarat_prices', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_pex', models.IntegerField(default=0)),
                ('per_pex', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_prices', to='organization.organization')),
            ],
        ),
    ]
