# Generated by Django 4.2.1 on 2025-07-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_riyalrate_is_food_pkr_riyalrate_is_ziarat_pkr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customumrahpackagehoteldetails',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
