# Generated by Django 4.2.1 on 2025-07-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_customumrahpackagehoteldetails_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUmrahZiaratDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziarat_details', to='packages.customumrahpackage')),
                ('ziarat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.ziaratprice')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUmrahFoodDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.foodprice')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_details', to='packages.customumrahpackage')),
            ],
        ),
    ]
