# Generated by Django 4.2.1 on 2025-08-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_customumrahziaratdetails_customumrahfooddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlyvisaprice',
            name='airpot_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
