# Generated by Django 4.2.1 on 2025-09-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_alter_onlyvisaprice_airpot_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ziaratprice',
            old_name='Name',
            new_name='ziarat_title',
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ziarat_prices', to='packages.city'),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
