# Generated by Django 4.2.1 on 2025-09-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_rename_name_ziaratprice_ziarat_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_prices', to='packages.city'),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
