# Generated by Django 4.2.1 on 2025-09-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_foodprice_city_foodprice_description_foodprice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziaratprice',
            name='max_pex',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='min_pex',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ziaratprice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
