# Generated by Django 4.2.1 on 2025-09-18 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_ziaratprice_max_pex_ziaratprice_min_pex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlyvisaprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='only_visa_prices', to='packages.city'),
        ),
        migrations.AddField(
            model_name='onlyvisaprice',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, null=True),
        ),
    ]
