# Generated by Django 4.2.1 on 2025-09-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_bookinghoteldetails_check_in_status_and_more'),
        ('packages', '0017_onlyvisaprice_city_onlyvisaprice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahvisapricetwo',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umrah_visa_prices_two', to='booking.vehicletype'),
        ),
    ]
