# Generated by Django 4.2.1 on 2025-09-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_umrahvisapricetwo_vehicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umrahpackagehoteldetails',
            old_name='check_in_time',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='umrahpackagehoteldetails',
            old_name='check_out_time',
            new_name='check_out_date',
        ),
    ]
