# Generated by Django 4.2.1 on 2025-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_rename_check_in_time_umrahpackagehoteldetails_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahpackage',
            name='booked_seats',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='confirmed_seats',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='left_seats',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='umrahpackage',
            name='total_seats',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
