# Generated by Django 4.2.1 on 2025-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_umrahpackage_booked_seats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customumrahpackagehoteldetails',
            old_name='check_in_time',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='customumrahpackagehoteldetails',
            old_name='check_out_time',
            new_name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='umrahpackagetransportdetails',
            name='transport_sector',
        ),
        migrations.AlterField(
            model_name='transportsectorprice',
            name='vehicle_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
