# Generated by Django 4.2.1 on 2025-09-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0021_rename_check_in_time_customumrahpackagehoteldetails_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umrahpackagetransportdetails',
            name='vehicle_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
