# Generated by Django 4.2.1 on 2025-09-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0022_alter_umrahpackagetransportdetails_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customumrahpackagetransportdetails',
            name='transport_sector',
        ),
        migrations.AddField(
            model_name='umrahpackagetransportdetails',
            name='transport_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.transportsectorprice'),
        ),
        migrations.AlterField(
            model_name='customumrahpackagetransportdetails',
            name='vehicle_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
