# Generated by Django 4.2.1 on 2025-09-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0023_remove_customumrahpackagetransportdetails_transport_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customumrahpackage',
            name='agent',
        ),
    ]
