# Generated by Django 4.2.1 on 2025-09-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0024_remove_customumrahpackage_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlines',
            name='is_umrah_seat',
            field=models.BooleanField(default=True),
        ),
    ]
