# Generated by Django 4.2.1 on 2025-09-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_rename_notes_booking_rejected_notes'),
        ('packages', '0025_airlines_is_umrah_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umrahvisapricetwo',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='umrahvisapricetwo',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, related_name='umrah_visa_prices_two', to='booking.vehicletype'),
        ),
    ]
