# Generated by Django 4.2.1 on 2025-09-23 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0026_remove_umrahvisapricetwo_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customumrahpackage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_umrah_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
