# Generated by Django 4.2.1 on 2025-09-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0027_customumrahpackage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahpackage',
            name='inventory_owner_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
