# Generated by Django 4.2.1 on 2025-09-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0028_umrahpackage_inventory_owner_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahpackagetransportdetails',
            name='transport_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
