"""Add public booking related fields to UmrahPackage

Generated by assistant.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0030_umrahpackage_resell_commission"),
    ]

    operations = [
        migrations.AddField(
            model_name="umrahpackage",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="umrahpackage",
            name="available_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="umrahpackage",
            name="available_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="umrahpackage",
            name="price_per_person",
            field=models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=12),
        ),
        migrations.AddField(
            model_name="umrahpackage",
            name="min_partial_percent",
            field=models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name="umrahpackage",
            name="min_partial_amount",
            field=models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=12),
        ),
    ]
