# Generated by Django 4.2.1 on 2025-08-15 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0012_customumrahziaratdetails_customumrahfooddetails'),
        ('tickets', '0007_remove_hotelprices_double_price_and_more'),
        ('organization', '0005_agency_logo'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_title', models.CharField(max_length=100)),
                ('account_number', models.TextField(blank=True, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BookingHotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateField(blank=True, null=True)),
                ('check_out_time', models.DateField(blank=True, null=True)),
                ('number_of_nights', models.IntegerField(default=0)),
                ('room_type', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPersonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('person_title', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('passpoet_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('passport_picture', models.ImageField(blank=True, null=True, upload_to='media/passport_pictures')),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('visa_price', models.FloatField(default=0)),
                ('food_price', models.FloatField(default=0)),
                ('makkah_ziyarat_price', models.FloatField(default=0)),
                ('madinah_ziyarat_price', models.FloatField(default=0)),
                ('ticket_price', models.FloatField(default=0)),
                ('is_family_head', models.BooleanField(default=False)),
                ('visa_status', models.CharField(default='Pending', max_length=20)),
                ('ticket_status', models.CharField(default='Pending', max_length=20)),
                ('ticket_remarks', models.TextField(blank=True, null=True)),
                ('voucher_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_meal_included', models.BooleanField(default=False)),
                ('is_refundable', models.BooleanField(default=False)),
                ('pnr', models.CharField(max_length=100)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('adult_price', models.FloatField(default=0)),
                ('seats', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('pieces', models.IntegerField(default=0)),
                ('is_umrah_seat', models.BooleanField(default=False)),
                ('trip_type', models.CharField(max_length=50)),
                ('departure_stay_type', models.CharField(max_length=50)),
                ('return_stay_type', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTicketStopoverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopover_duration', models.CharField(max_length=100)),
                ('trip_type', models.CharField(max_length=50)),
                ('stopover_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.city')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopover_details', to='booking.bookingticketdetails')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTicketTicketTripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date_time', models.DateTimeField()),
                ('arrival_date_time', models.DateTimeField()),
                ('trip_type', models.CharField(max_length=50)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_arrival_city', to='packages.city')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_departure_city', to='packages.city')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_details', to='booking.bookingticketdetails')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/payment_receipts')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organization.agency')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.bank')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='custom_package',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_hotel_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_pax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_ticket_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_transport_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_visa_amount',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='BookingDetail',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='transport_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.transportsectorprice'),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_details', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_details', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='shirka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.shirka'),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.hotels'),
        ),
    ]
