# Generated by Django 4.2.1 on 2025-08-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bank_bookinghoteldetails_bookingpersondetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingpersondetail',
            old_name='madinah_ziyarat_price',
            new_name='ziyarat_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='makkah_ziyarat_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_partial_payment_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_adult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_child',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_infant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='is_price_pkr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='riyal_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='family_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='is_food_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='is_visa_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='is_ziyarat_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='is_price_pkr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='riyal_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='is_price_pkr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='riyal_rate',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='BookingPersonZiyaratDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('price', models.FloatField(default=0)),
                ('is_price_pkr', models.BooleanField(default=True)),
                ('riyal_rate', models.FloatField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyarat_details', to='booking.bookingpersondetail')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPersonFoodDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('is_price_pkr', models.BooleanField(default=True)),
                ('riyal_rate', models.FloatField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_details', to='booking.bookingpersondetail')),
            ],
        ),
    ]
