# Generated by Django 4.2.1 on 2025-08-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_alter_onlyvisaprice_airpot_name'),
        ('booking', '0003_rename_madinah_ziyarat_price_bookingpersondetail_ziyarat_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='voucher_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='food_brn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='food_voucher_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ticker_brn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ticket_voucher_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='transport_brn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='transport_voucher_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='visa_group_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ziyarat_brn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ziyarat_voucher_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='shirka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.shirka'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
