# Generated by Django 4.2.1 on 2025-08-22 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_bookingpersondetail_voucher_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='food_price',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='ziyarat_price',
        ),
        migrations.RemoveField(
            model_name='bookingtransportdetails',
            name='quantity',
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BookingPersonContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='booking.bookingpersondetail')),
            ],
        ),
    ]
