# Generated by Django 4.2.1 on 2025-09-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_agency_logo'),
        ('booking', '0007_alter_sector_organization_alter_sector_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='organization.organization'),
        ),
        migrations.AlterModelTable(
            name='sector',
            table='small_sector',
        ),
        migrations.CreateModel(
            name='BigSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bog_sectors', to='organization.organization')),
            ],
            options={
                'db_table': 'big_sector',
            },
        ),
    ]
