# Generated by Django 4.2.1 on 2025-09-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_vehicletype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinghoteldetails',
            old_name='check_in_time',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='bookinghoteldetails',
            old_name='check_out_time',
            new_name='check_out_date',
        ),
    ]
