# Generated by Django 4.2.1 on 2025-09-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_check_in_time_bookinghoteldetails_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='contact_person_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
