# Generated by Django 4.2.1 on 2025-09-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_foodprice_city_foodprice_description_foodprice_price'),
        ('booking', '0011_bookinghoteldetails_contact_person_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='sector_name',
        ),
        migrations.AddField(
            model_name='sector',
            name='arrival_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_sectors', to='packages.city'),
        ),
        migrations.AddField(
            model_name='sector',
            name='departure_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_sectors', to='packages.city'),
        ),
    ]
