# Generated by Django 4.2.1 on 2025-09-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_sector_sector_name_sector_arrival_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtransportdetails',
            name='vehicle_type',
        ),
    ]
