# Generated by Django 4.2.1 on 2025-09-17 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_bookingtransportdetails_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_details', to='booking.vehicletype'),
        ),
    ]
