# Generated by Django 4.2.1 on 2025-09-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_bookingtransportdetails_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtransportdetails',
            name='transport_sector',
        ),
    ]
