# Generated by Django 4.2.1 on 2025-09-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_bookingtransportdetails_transport_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='food_brn',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='food_voucher_number',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='ticker_brn',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='ticket_voucher_number',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='transport_brn',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='transport_voucher_number',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='ziyarat_brn',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='ziyarat_voucher_number',
        ),
    ]
