# Generated by Django 4.2.1 on 2025-09-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_remove_bookingpersondetail_food_brn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpersondetail',
            name='food_brn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='food_voucher_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ticker_brn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ticket_voucher_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='transport_brn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='transport_voucher_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ziyarat_brn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ziyarat_voucher_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
