# Generated by Django 4.2.1 on 2025-09-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_bookingpersondetail_food_brn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingticketdetails',
            name='is_price_pkr',
        ),
        migrations.RemoveField(
            model_name='bookingticketdetails',
            name='riyal_rate',
        ),
    ]
