# Generated by Django 4.2.1 on 2025-09-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_bookingticketdetails_is_price_pkr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='food_brn',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='food_voucher_number',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='ticker_brn',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='ticket_voucher_number',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='transport_brn',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='transport_voucher_number',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='ziyarat_brn',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='ziyarat_voucher_number',
        ),
    ]
