# Generated by Django 4.2.1 on 2025-09-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_remove_bookingpersondetail_food_brn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigsector',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='bigsector',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='bigsector',
            name='sector_name',
        ),
        migrations.AddField(
            model_name='bigsector',
            name='small_sectors',
            field=models.ManyToManyField(related_name='big_sectors', to='booking.sector'),
        ),
        migrations.AlterModelTable(
            name='bigsector',
            table=None,
        ),
    ]
