# Generated by Django 4.2.1 on 2025-09-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_agency_logo'),
        ('booking', '0020_remove_bigsector_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigsector',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big_sectors', to='organization.organization'),
        ),
        migrations.AlterModelTable(
            name='bigsector',
            table='big_sector',
        ),
    ]
