# Generated by Django 4.2.1 on 2025-09-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_bigsector_organization_alter_bigsector_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicletype',
            old_name='type',
            new_name='visa_type',
        ),
    ]
