# Generated by Django 4.2.1 on 2025-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_rename_type_vehicletype_visa_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='check_in_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='check_out_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='leg_no',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
