# Generated by Django 4.2.1 on 2025-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
