# Generated by Django 4.2.1 on 2025-09-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_booking_action_booking_notes_booking_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='hotel_brn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='hotel_voucher_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='total_in_pkr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='total_in_riyal_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
