# Generated by Django 4.2.1 on 2025-09-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_umrahvisapricetwo_vehicle_type'),
        ('booking', '0026_bookinghoteldetails_hotel_brn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='call_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pending_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_food_amount_pkr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_food_amount_sar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_hotel_amount_pkr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_hotel_amount_sar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_in_pkr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_ticket_amount_pkr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_transport_amount_pkr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_transport_amount_sar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_visa_amount_pkr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_visa_amount_sar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_ziyarat_amount_pkr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_ziyarat_amount_sar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='umrah_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.umrahpackage'),
        ),
    ]
