# Generated by Django 4.2.1 on 2025-09-19 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0027_booking_call_status_booking_client_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(max_length=255)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='internal_notes/')),
                ('working_status', models.CharField(choices=[('clear', 'Clear'), ('not_clear', 'Not Clear')], default='not_clear', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
