# Generated by Django 4.2.1 on 2025-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_internalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpersondetail',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='this_pex_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ticket_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='ticket_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='visa_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
