# Generated by Django 4.2.1 on 2025-09-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_bookingpersondetail_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTransportSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_no', models.IntegerField(default=0)),
                ('small_sector_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('brn_no', models.CharField(blank=True, max_length=100, null=True)),
                ('transport_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='booking.bookingtransportdetails')),
            ],
        ),
    ]
