# Generated by Django 4.2.1 on 2025-09-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_bookingtransportsector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtransportsector',
            name='transport_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_details', to='booking.bookingtransportdetails'),
        ),
    ]
