# Generated by Django 4.2.1 on 2025-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_alter_bookingtransportsector_transport_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='brn_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='price_in_pkr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='price_in_sar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
