# Generated by Django 4.2.1 on 2025-09-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_booking_is_visa_price_pkr_booking_visa_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='self_hotel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='sharing_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
