# Generated by Django 4.2.1 on 2025-09-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_bookinghoteldetails_self_hotel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='is_food_included',
        ),
        migrations.RemoveField(
            model_name='bookingpersondetail',
            name='is_ziyarat_included',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_food_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_ziyarat_included',
            field=models.BooleanField(default=False),
        ),
    ]
