# Generated by Django 4.2.1 on 2025-09-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_remove_bookingpersondetail_is_food_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal', to='booking.internalnote'),
        ),
    ]
