# Generated by Django 4.2.1 on 2025-09-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_booking_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
