# Generated by Django 4.2.1 on 2025-09-20 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0037_internalnote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejected_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
