# Generated by Django 4.2.1 on 2025-09-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_booking_rejected_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpersonziyaratdetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersonziyaratdetails',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersonziyaratdetails',
            name='per_pax_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingpersonziyaratdetails',
            name='price_in_sar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingpersonziyaratdetails',
            name='total_pax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingpersonziyaratdetails',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingpersonziyaratdetails',
            name='total_price_in_pkr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookingpersonziyaratdetails',
            name='ziyarar_voucher_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersonziyaratdetails',
            name='ziyarat_brn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
