# Generated by Django 4.2.1 on 2025-09-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_bookingpersonfooddetails_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpersondetail',
            name='is_visa_price_pkr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='visa_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='visa_rate_in_pkr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='visa_rate_in_sar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='visa_riyal_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
