# Generated by Django 4.2.1 on 2025-09-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_bookingpersondetail_is_visa_price_pkr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='internal',
        ),
        migrations.AddField(
            model_name='booking',
            name='internals',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.internalnote'),
        ),
    ]
