# Generated by Django 4.2.1 on 2025-09-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_remove_booking_internal_booking_internals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpersondetail',
            name='ticket_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpersondetail',
            name='ticket_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
