# Generated by Django 4.2.1 on 2025-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_alter_bookingpersondetail_ticket_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpersondetail',
            name='ticket_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingpersondetail',
            name='ticket_price',
            field=models.FloatField(default=0),
        ),
    ]
