# Generated by Django 4.2.1 on 2025-09-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_alter_bookingpersondetail_ticket_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='notes',
            new_name='rejected_notes',
        ),
    ]
