# Generated by Django 4.2.1 on 2025-09-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='selling_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='internals',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookings', to='booking.internalnote'),
        ),
    ]
