# Generated by Django 4.2.1 on 2025-09-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_agency_logo'),
        ('booking', '0048_booking_owner_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organization.agency'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, null=True),
        ),
    ]
