# Generated by Django 4.2.1 on 2025-09-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_organizationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='inventory_owner_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='markup_by_reseller',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reseller_commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
