# Generated by Django 4.2.1 on 2025-09-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_agency_logo'),
        ('booking', '0051_booking_booking_organization_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedReseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.JSONField(default=list)),
                ('requested_status_by_reseller', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('commission_group_id', models.IntegerField(blank=True, null=True)),
                ('markup_group_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_resellers', to='organization.organization')),
                ('reseller_companies', models.ManyToManyField(related_name='reseller_links', to='organization.organization')),
            ],
        ),
    ]
