# Generated by Django 4.2.1 on 2025-09-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_allowedreseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedreseller',
            name='inventory_owner_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_resellers', to='booking.organizationlink'),
        ),
    ]
