# Generated by Django 4.2.1 on 2025-09-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_alter_allowedreseller_inventory_owner_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlink',
            name='request_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
