# Generated by Django 4.2.1 on 2025-09-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_agency_logo'),
        ('booking', '0054_organizationlink_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_groups', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things', models.CharField(choices=[('group_ticket', 'Group Ticket'), ('umrah_package', 'Umrah Package'), ('hotel', 'Hotel')], max_length=50)),
                ('group_ticket_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('umrah_package_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('PKR', 'PKR'), ('SAR', 'SAR')], default='PKR', max_length=10)),
                ('room_type', models.CharField(blank=True, choices=[('quint', 'Quint'), ('quad', 'Quad'), ('triple', 'Triple'), ('double', 'Double'), ('sharing', 'Sharing'), ('all', 'All Types')], max_length=50, null=True)),
                ('per_night_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discounted_hotels', models.IntegerField(blank=True, null=True)),
                ('discount_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='booking.discountgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='organization.organization')),
            ],
        ),
    ]
