# Generated by Django 4.2.1 on 2025-09-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0055_discountgroup_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('applies_to', models.CharField(choices=[('group_ticket', 'Group Ticket'), ('hotel', 'Hotel'), ('umrah_package', 'Umrah Package')], max_length=20)),
                ('ticket_markup', models.FloatField(blank=True, default=0, null=True)),
                ('hotel_per_night_markup', models.FloatField(blank=True, default=0, null=True)),
                ('umrah_package_markup', models.FloatField(blank=True, default=0, null=True)),
                ('organization_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
