# Generated by assistant - add booking_type, is_full_package, payments, journal_items
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0060_add_ticket_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(choices=[('TICKET', 'Ticket'), ('UMRAH', 'Umrah Package'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], default='TICKET', max_length=20),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_full_package",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="payments",
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="journal_items",
            field=models.JSONField(default=list, blank=True),
        ),
    ]
