# Generated by Django 4.2.1 on 2025-10-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_owner_reselling'),
        ('booking', '0064_add_payment_agent_org_bank_kuickpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discounted_hotels',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='tickets.hotels'),
        ),
    ]
