# Generated by Django 4.2.1 on 2025-10-28 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_organizationlink_options'),
        ('booking', '0065_alter_discount_discounted_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='inventory_owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_hotel_inventory', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='inventory_owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_ticket_inventory', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='inventory_owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_transport_inventory', to='organization.organization'),
        ),
    ]
