# Generated by Django 4.2.1 on 2025-10-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0066_bookinghoteldetails_inventory_owner_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_walkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='linked_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_walkins', to='booking.booking'),
        ),
    ]
