# Generated by Django 4.2.1 on 2025-10-30 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0067_bookingcallremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_outsourced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='outsourced_hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HotelOutsourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('source_company', models.CharField(blank=True, max_length=255, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, max_length=100, null=True)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('number_of_nights', models.IntegerField(default=1)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('agent_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ledger_entry_id', models.IntegerField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outsourcing_records', to='booking.booking')),
                ('booking_hotel_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outsourcing', to='booking.bookinghoteldetails')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='hoteloutsourcing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('booking', 'booking_hotel_detail'), name='unique_active_outsource_per_hoteldetail'),
        ),
    ]
