"""Add fields to support public umrah bookings and payments

Generated by assistant.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0069_add_public_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_public_booking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="created_by_user_type",
            field=models.CharField(max_length=30, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="invoice_no",
            field=models.CharField(max_length=64, null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_payment_received",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="public_mode",
            field=models.BooleanField(default=False),
        ),
    ]
