"""Add forwarded_at and forwarded_response to FormSubmission

Generated by assistant
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="forwarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="forwarded_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
