"""Create FormSubmissionTask model

Generated by assistant
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_add_forwarding_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmissionTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("next_try_at", models.DateTimeField(db_index=True)),
                ("locked", models.BooleanField(default=False, db_index=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("done", "Done"), ("failed", "Failed")], default="pending", max_length=16)),
                ("last_error", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="forward_tasks", to="blog.formsubmission")),
            ],
            options={
                "indexes": [models.Index(fields=["status", "next_try_at"], name="blog_formsubmissiontask_status_next_idx")],
            },
        ),
    ]
