"""Add form_unique_id and form_page_url to LeadForm

Generated by assistant
"""
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_create_formsubmissiontask"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadform",
            name="form_unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="leadform",
            name="form_page_url",
            field=models.SlugField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
