# Generated by Django 4.2.1 on 2025-10-30 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_leadform_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='formsubmissiontask',
            new_name='blog_formsu_status_43e60a_idx',
            old_name='blog_formsubmissiontask_status_next_idx',
        ),
        migrations.AlterField(
            model_name='formsubmissiontask',
            name='next_try_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
