# Generated by Django 4.2.1 on 2025-10-27 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=16)),
                ('model_name', models.CharField(max_length=128)),
                ('object_id', models.CharField(max_length=64)),
                ('performed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='UniversalIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(max_length=32, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'universal_id_sequence',
            },
        ),
        migrations.CreateModel(
            name='UniversalRegistration',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('organization', 'Organization'), ('branch', 'Branch'), ('agent', 'Agent'), ('employee', 'Employee')], max_length=16)),
                ('organization_id', models.CharField(blank=True, max_length=32, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('contact_no', models.CharField(blank=True, max_length=32, null=True)),
                ('cnic', models.CharField(blank=True, max_length=32, null=True)),
                ('cnic_front', models.CharField(blank=True, max_length=1024, null=True)),
                ('cnic_back', models.CharField(blank=True, max_length=1024, null=True)),
                ('visiting_card', models.CharField(blank=True, max_length=1024, null=True)),
                ('dts_license', models.CharField(blank=True, max_length=1024, null=True)),
                ('license_no', models.CharField(blank=True, max_length=128, null=True)),
                ('ntn_no', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(default='Pakistan', max_length=64)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='universal.universalregistration')),
            ],
            options={
                'db_table': 'universal_registration',
                'indexes': [models.Index(fields=['type'], name='universal_r_type_dff7d4_idx'), models.Index(fields=['organization_id'], name='universal_r_organiz_18b222_idx'), models.Index(fields=['branch_id'], name='universal_r_branch__0fc32a_idx')],
            },
        ),
    ]
