# Generated by Django 4.2.1 on 2025-10-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('organization', 'Organization'), ('branch', 'Branch'), ('agent', 'Agent'), ('employee', 'Employee')], max_length=20)),
                ('requirement_text', models.TextField()),
                ('benefit_text', models.TextField()),
                ('city_needed', models.CharField(blank=True, help_text='Required only for branch (optional)', max_length=100, null=True)),
                ('service_allowed', models.CharField(blank=True, help_text='Allowed services (for agent, optional)', max_length=200, null=True)),
                ('post_available', models.CharField(blank=True, help_text='Post options (for employee, optional)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
