# Generated by Django 4.2.1 on 2025-10-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal', '0002_registrationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaxMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pax_id', models.CharField(help_text='Linked to booking/passenger', max_length=100)),
                ('flight_no', models.CharField(max_length=50)),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('in_pakistan', 'In Pakistan'), ('entered_ksa', 'Entered KSA'), ('in_ksa', 'In KSA'), ('exited_ksa', 'Exited KSA'), ('exit_pending', 'Exit Pending')], default='in_pakistan', max_length=20)),
                ('verified_exit', models.BooleanField(default=False)),
                ('agent_id', models.CharField(help_text='Linked agent/organization', max_length=100)),
                ('reported_to_shirka', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
