# Generated by Django 4.2.1 on 2025-10-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_is_active_alter_customer_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
