# Generated by Django 5.2.7 on 2025-10-23 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('organization', '0001_initial'),
        ('packages', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='umrah_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.umrahpackage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='bookinghoteldetails',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.hotels'),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_details', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='bookingpersondetail',
            name='shirka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.shirka'),
        ),
        migrations.AddField(
            model_name='bookingpersoncontactdetails',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='booking.bookingpersondetail'),
        ),
        migrations.AddField(
            model_name='bookingpersonfooddetails',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_details', to='booking.bookingpersondetail'),
        ),
        migrations.AddField(
            model_name='bookingpersonziyaratdetails',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyarat_details', to='booking.bookingpersondetail'),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_details', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='bookingticketdetails',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='bookingticketstopoverdetails',
            name='stopover_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.city'),
        ),
        migrations.AddField(
            model_name='bookingticketstopoverdetails',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopover_details', to='booking.bookingticketdetails'),
        ),
        migrations.AddField(
            model_name='bookingtickettickettripdetails',
            name='arrival_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_arrival_city', to='packages.city'),
        ),
        migrations.AddField(
            model_name='bookingtickettickettripdetails',
            name='departure_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_departure_city', to='packages.city'),
        ),
        migrations.AddField(
            model_name='bookingtickettickettripdetails',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_details', to='booking.bookingticketdetails'),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='shirka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.shirka'),
        ),
        migrations.AddField(
            model_name='bookingtransportsector',
            name='transport_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_details', to='booking.bookingtransportdetails'),
        ),
        migrations.AddField(
            model_name='discount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='discountgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_groups', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='booking.discountgroup'),
        ),
        migrations.AddField(
            model_name='internalnote',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='internals',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookings', to='booking.internalnote'),
        ),
        migrations.AddField(
            model_name='allowedreseller',
            name='inventory_owner_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_resellers', to='booking.organizationlink'),
        ),
        migrations.AddField(
            model_name='payment',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organization.agency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.bank'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='sector',
            name='arrival_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_sectors', to='packages.city'),
        ),
        migrations.AddField(
            model_name='sector',
            name='departure_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_sectors', to='packages.city'),
        ),
        migrations.AddField(
            model_name='sector',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='bigsector',
            name='small_sectors',
            field=models.ManyToManyField(related_name='big_sectors', to='booking.sector'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='big_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_types', to='booking.bigsector'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='small_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_types', to='booking.sector'),
        ),
        migrations.AddField(
            model_name='bookingtransportdetails',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_details', to='booking.vehicletype'),
        ),
    ]
