# Generated by Django 5.2.7 on 2025-10-24 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedreseller',
            old_name='commission_group_id',
            new_name='discount_group_id',
        ),
        migrations.RemoveField(
            model_name='organizationlink',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='organizationlink',
            name='link_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_link', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationlink',
            name='main_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_link', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='allowedreseller',
            name='allowed',
            field=models.JSONField(choices=[('UMRAH_PACKAGES', 'Umrah Packages'), ('GROUP_TICKETS', 'Group Tickets'), ('HOTELS', 'Hotels')], default=list),
        ),
    ]
