# Generated by Django 5.2.7 on 2025-10-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_commission_group_id_allowedreseller_discount_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedreseller',
            name='allowed',
            field=models.CharField(blank=True, choices=[('UMRAH_PACKAGES', 'Umrah Packages'), ('GROUP_TICKETS', 'Group Tickets'), ('HOTELS', 'Hotels')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingticketdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
