# Generated by Django 4.2.1 on 2025-10-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_allowedreseller_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedreseller',
            name='allowed',
            field=models.CharField(blank=True, choices=[('UMRAH_PACKAGES', 'Umrah Packages'), ('GROUP_TICKETS', 'Group Tickets'), ('HOTELS', 'Hotels')], max_length=255, null=True),
        ),
    ]
