# Generated by Django 4.2.1 on 2025-10-27 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0013_remove_hotels_google_drive_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.CharField(help_text="Floor number (e.g., 'G', '1', '2', 'M' for mezzanine)", max_length=10)),
                ('room_no', models.CharField(help_text="Room number (e.g., '101', '202A')", max_length=20)),
                ('beds', models.IntegerField(default=1, help_text='Total number of beds in this room')),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('blocked', 'Blocked')], default='available', help_text='Current availability status of the room', max_length=20)),
                ('room_type', models.CharField(blank=True, help_text="Room type (e.g., 'Single', 'Double', 'Suite')", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_maps_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(help_text='Hotel to which this room belongs', on_delete=django.db.models.deletion.CASCADE, related_name='room_mappings', to='tickets.hotels')),
            ],
            options={
                'verbose_name': 'Room Map',
                'verbose_name_plural': 'Room Maps',
                'db_table': 'operations_roommap',
                'ordering': ['hotel', 'floor_no', 'room_no'],
                'indexes': [models.Index(fields=['hotel', 'availability_status'], name='operations__hotel_i_7c6091_idx'), models.Index(fields=['floor_no', 'room_no'], name='operations__floor_n_835853_idx')],
                'unique_together': {('hotel', 'room_no')},
            },
        ),
    ]
