# Generated by Django 4.2.1 on 2025-10-27 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0013_remove_hotels_google_drive_link'),
        ('booking', '0065_alter_discount_discounted_hotels'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_id_str', models.CharField(help_text='Passenger ID from BookingPersonDetail', max_length=50)),
                ('pax_first_name', models.CharField(help_text='Passenger first name', max_length=100)),
                ('pax_last_name', models.CharField(help_text='Passenger last name', max_length=100)),
                ('booking_id_str', models.CharField(help_text='Booking ID for quick reference', max_length=50)),
                ('contact_no', models.CharField(blank=True, help_text='Passenger contact number', max_length=20, null=True)),
                ('family_head_contact', models.CharField(blank=True, help_text='Family head contact number', max_length=20, null=True)),
                ('hotel_name', models.CharField(help_text='Hotel name (denormalized)', max_length=200)),
                ('city', models.CharField(help_text='City where hotel is located (e.g., Makkah, Madinah)', max_length=100)),
                ('room_no', models.CharField(blank=True, help_text='Room number (denormalized from RoomMap)', max_length=20, null=True)),
                ('bed_no', models.CharField(blank=True, help_text='Bed number within the room', max_length=10, null=True)),
                ('date', models.DateField(help_text='Operation date for daily tracking (check-in or check-out date)')),
                ('check_in_date', models.DateField(help_text='Scheduled/actual check-in date')),
                ('check_out_date', models.DateField(help_text='Scheduled/actual check-out date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('canceled', 'Canceled'), ('no_show', 'No Show')], default='pending', help_text='Current operation status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='Booking reference', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_operations', to='booking.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_operations_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(help_text='Hotel where pax is staying', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_operations', to='tickets.hotels')),
                ('pax', models.ForeignKey(help_text='Passenger/person details from booking', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_operations', to='booking.bookingpersondetail')),
                ('room', models.ForeignKey(blank=True, help_text='Room assigned to pax', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_operations', to='operations.roommap')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_operations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel Operation',
                'verbose_name_plural': 'Hotel Operations',
                'db_table': 'operations_hoteloperations',
                'ordering': ['date', 'hotel', 'booking'],
                'indexes': [models.Index(fields=['date', 'status'], name='operations__date_a2f90f_idx'), models.Index(fields=['booking', 'pax'], name='operations__booking_ba3b6f_idx'), models.Index(fields=['hotel', 'date'], name='operations__hotel_i_154846_idx'), models.Index(fields=['check_in_date'], name='operations__check_i_39b497_idx'), models.Index(fields=['check_out_date'], name='operations__check_o_2e8535_idx'), models.Index(fields=['pax_id_str'], name='operations__pax_id__564a04_idx'), models.Index(fields=['booking_id_str'], name='operations__booking_0d37d8_idx')],
            },
        ),
    ]
