# Generated by Django 4.2.1 on 2025-10-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_hoteloperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteloperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', help_text='Current operation status', max_length=20),
        ),
    ]
