# Generated by Django 4.2.1 on 2025-10-27 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0065_alter_discount_discounted_hotels'),
        ('operations', '0003_alter_hoteloperation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteloperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('canceled', 'Canceled')], default='pending', help_text='Current operation status', max_length=20),
        ),
        migrations.CreateModel(
            name='TransportOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_id_str', models.CharField(help_text='Passenger ID from BookingPersonDetail', max_length=50)),
                ('pax_first_name', models.CharField(help_text='Passenger first name', max_length=100)),
                ('pax_last_name', models.CharField(help_text='Passenger last name', max_length=100)),
                ('booking_id_str', models.CharField(help_text='Booking ID for quick reference', max_length=50)),
                ('contact_no', models.CharField(blank=True, help_text='Passenger contact number', max_length=20, null=True)),
                ('pickup_location', models.CharField(help_text='Pickup location (hotel name or address)', max_length=200)),
                ('drop_location', models.CharField(help_text='Drop location (hotel name or address)', max_length=200)),
                ('vehicle_name', models.CharField(blank=True, help_text='Vehicle name (denormalized)', max_length=100, null=True)),
                ('driver_name', models.CharField(blank=True, help_text='Driver name', max_length=100, null=True)),
                ('driver_contact', models.CharField(blank=True, help_text='Driver contact number', max_length=20, null=True)),
                ('date', models.DateField(help_text='Transport operation date for daily tracking')),
                ('pickup_time', models.TimeField(blank=True, help_text='Scheduled pickup time', null=True)),
                ('actual_pickup_time', models.TimeField(blank=True, help_text='Actual pickup time', null=True)),
                ('actual_drop_time', models.TimeField(blank=True, help_text='Actual drop time', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('canceled', 'Canceled')], default='pending', help_text='Current transport operation status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='Booking reference', on_delete=django.db.models.deletion.CASCADE, related_name='transport_operations', to='booking.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_operations_created', to=settings.AUTH_USER_MODEL)),
                ('pax', models.ForeignKey(help_text='Passenger/person details from booking', on_delete=django.db.models.deletion.CASCADE, related_name='transport_operations', to='booking.bookingpersondetail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_operations_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, help_text='Vehicle assigned for transport', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_operations', to='booking.vehicletype')),
            ],
            options={
                'verbose_name': 'Transport Operation',
                'verbose_name_plural': 'Transport Operations',
                'db_table': 'operations_transportoperations',
                'ordering': ['date', 'pickup_time', 'booking'],
                'indexes': [models.Index(fields=['date', 'status'], name='operations__date_620b34_idx'), models.Index(fields=['booking', 'pax'], name='operations__booking_049291_idx'), models.Index(fields=['date', 'pickup_location'], name='operations__date_426f7e_idx'), models.Index(fields=['pax_id_str'], name='operations__pax_id__6b4196_idx'), models.Index(fields=['booking_id_str'], name='operations__booking_65f9d8_idx')],
            },
        ),
    ]
