# Generated by Django 4.2.1 on 2025-10-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_hoteloperation_status_transportoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', help_text='Current transport operation status', max_length=20),
        ),
    ]
