# Generated by Django 4.2.1 on 2025-10-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_transportoperation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('canceled', 'Canceled')], default='pending', help_text='Current transport operation status', max_length=20),
        ),
    ]
