# Generated by Django 4.2.1 on 2025-10-28 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0065_alter_discount_discounted_hotels'),
        ('operations', '0006_alter_transportoperation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_id_str', models.CharField(help_text='Passenger ID from BookingPersonDetail', max_length=50)),
                ('pax_first_name', models.CharField(help_text='Passenger first name', max_length=100)),
                ('pax_last_name', models.CharField(help_text='Passenger last name', max_length=100)),
                ('booking_id_str', models.CharField(help_text='Booking ID for quick reference', max_length=50)),
                ('contact_no', models.CharField(blank=True, help_text='Passenger contact number', max_length=20, null=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], help_text='Type of meal (breakfast/lunch/dinner/snack)', max_length=20)),
                ('location', models.CharField(help_text='Restaurant or hotel name where meal is served', max_length=200)),
                ('city', models.CharField(blank=True, help_text='City where meal is served', max_length=100, null=True)),
                ('date', models.DateField(help_text='Date of meal service')),
                ('meal_time', models.TimeField(blank=True, help_text='Scheduled meal time', null=True)),
                ('actual_serve_time', models.DateTimeField(blank=True, help_text='Actual time meal was served', null=True)),
                ('special_requirements', models.TextField(blank=True, help_text='Dietary restrictions, allergies, special requests', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('served', 'Served'), ('canceled', 'Canceled')], default='pending', help_text='Current meal status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='Booking reference', on_delete=django.db.models.deletion.CASCADE, related_name='food_operations', to='booking.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_operations_created', to=settings.AUTH_USER_MODEL)),
                ('pax', models.ForeignKey(help_text='Passenger/person details from booking', on_delete=django.db.models.deletion.CASCADE, related_name='food_operations', to='booking.bookingpersondetail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_operations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Operation',
                'verbose_name_plural': 'Food Operations',
                'db_table': 'operations_foodoperations',
                'ordering': ['date', 'meal_time', 'booking'],
                'indexes': [models.Index(fields=['date', 'status'], name='operations__date_cdd103_idx'), models.Index(fields=['booking', 'pax'], name='operations__booking_0ebdde_idx'), models.Index(fields=['date', 'meal_type'], name='operations__date_52b840_idx'), models.Index(fields=['pax_id_str'], name='operations__pax_id__e72271_idx'), models.Index(fields=['booking_id_str'], name='operations__booking_dcfdcd_idx')],
            },
        ),
    ]
