# Generated by Django 4.2.1 on 2025-10-28 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0065_alter_discount_discounted_hotels'),
        ('operations', '0007_foodoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id_str', models.CharField(db_index=True, max_length=50)),
                ('pax_id_str', models.CharField(db_index=True, max_length=50)),
                ('pax_first_name', models.CharField(max_length=100)),
                ('pax_last_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('transfer_type', models.CharField(choices=[('pickup', 'Pickup from Airport'), ('drop', 'Drop to Airport')], db_index=True, max_length=10)),
                ('flight_number', models.CharField(db_index=True, max_length=20)),
                ('flight_time', models.TimeField()),
                ('date', models.DateField(db_index=True)),
                ('pickup_point', models.CharField(max_length=200)),
                ('drop_point', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('not_picked', 'Not Picked')], db_index=True, default='waiting', max_length=20)),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_operations', to='booking.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_airport_operations', to=settings.AUTH_USER_MODEL)),
                ('pax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_operations', to='booking.bookingpersondetail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_airport_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_airportoperations',
                'ordering': ['date', 'flight_time', 'booking'],
                'indexes': [models.Index(fields=['date', 'transfer_type'], name='operations__date_614263_idx'), models.Index(fields=['booking_id_str', 'status'], name='operations__booking_39f901_idx'), models.Index(fields=['flight_number', 'date'], name='operations__flight__42e178_idx')],
            },
        ),
    ]
