# Generated by Django 4.2.1 on 2025-10-28 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0065_alter_discount_discounted_hotels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0008_airportoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZiyaratOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id_str', models.CharField(db_index=True, help_text='Denormalized booking number', max_length=50)),
                ('pax_id_str', models.CharField(db_index=True, help_text='Denormalized pax ID', max_length=20)),
                ('pax_first_name', models.CharField(blank=True, max_length=100)),
                ('pax_last_name', models.CharField(blank=True, max_length=100)),
                ('pax_full_name', models.CharField(blank=True, max_length=200)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(help_text='Ziyarat location (e.g., Uhud Mountain, Quba Mosque)', max_length=200)),
                ('date', models.DateField(db_index=True, help_text='Date of ziyarat')),
                ('pickup_time', models.TimeField(help_text='Scheduled pickup time')),
                ('guide_name', models.CharField(blank=True, help_text='Tour guide name', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('not_picked', 'Not Picked')], db_index=True, default='pending', max_length=20)),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='Actual start time', null=True)),
                ('actual_completion_time', models.DateTimeField(blank=True, help_text='Actual completion time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this ziyarat', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyarat_operations', to='booking.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ziyarat_operations_created', to=settings.AUTH_USER_MODEL)),
                ('pax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyarat_operations', to='booking.bookingpersondetail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ziyarat_operations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ziyarat Operation',
                'verbose_name_plural': 'Ziyarat Operations',
                'ordering': ['date', 'pickup_time', 'location'],
                'indexes': [models.Index(fields=['date', 'status'], name='operations__date_ac188b_idx'), models.Index(fields=['booking_id_str', 'date'], name='operations__booking_3016ca_idx'), models.Index(fields=['location', 'date'], name='operations__locatio_f6ebb7_idx')],
            },
        ),
    ]
