# Generated by Django 4.2.1 on 2025-07-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
