# Generated by Django 4.2.1 on 2025-07-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_hotels_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
