# Generated by Django 4.2.1 on 2025-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_hotels_status_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='adult_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='child_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='infant_price',
            field=models.FloatField(default=0),
        ),
    ]
