# Generated by Django 4.2.1 on 2025-07-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_price_ticket_adult_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='tickets.hotels')),
            ],
        ),
    ]
