# Generated by Django 4.2.1 on 2025-07-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_hotelrooms_roomdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelprices',
            name='double_price',
        ),
        migrations.RemoveField(
            model_name='hotelprices',
            name='quad_price',
        ),
        migrations.RemoveField(
            model_name='hotelprices',
            name='quint_price',
        ),
        migrations.RemoveField(
            model_name='hotelprices',
            name='room_price',
        ),
        migrations.RemoveField(
            model_name='hotelprices',
            name='triple_price',
        ),
        migrations.AddField(
            model_name='hotelprices',
            name='is_sharing_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelprices',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
