# Generated by Django 4.2.1 on 2025-08-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_hotelprices_double_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seats',
            new_name='total_seats',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booked_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='confirmed_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='left_seats',
            field=models.IntegerField(default=0),
        ),
    ]
