# Generated by Django 4.2.1 on 2025-09-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_umrahvisapricetwo_vehicle_type'),
        ('tickets', '0008_rename_seats_ticket_total_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='packages.city'),
        ),
    ]
