# Generated by Django 4.2.1 on 2025-09-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_hotels_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='inventory_owner_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
