# Generated by Django 4.2.1 on 2025-10-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_owner_reselling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='google_drive_link',
        ),
    ]
