# Generated by Django 4.2.1 on 2025-10-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.BigIntegerField(blank=True, null=True)),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('applied_on_type', models.CharField(max_length=100)),
                ('receiver_type', models.CharField(max_length=50)),
                ('commission_type', models.CharField(max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition_type', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commission_rules',
            },
        ),
        migrations.CreateModel(
            name='CommissionEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.BigIntegerField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('earned_by_type', models.CharField(max_length=50)),
                ('earned_by_id', models.BigIntegerField(blank=True, null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemed_date', models.DateTimeField(blank=True, null=True)),
                ('ledger_tx_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commission_earnings',
                'indexes': [models.Index(fields=['booking_id'], name='commission__booking_41c914_idx'), models.Index(fields=['status'], name='commission__status_acb75e_idx'), models.Index(fields=['redeemed'], name='commission__redeeme_cb1e2c_idx')],
            },
        ),
    ]
