# Generated by Django 4.2.1 on 2025-10-30 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commissionearning',
            name='comm_e_booking_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='commissionearning',
            name='comm_e_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='commissionearning',
            name='comm_e_redeemed_idx',
        ),
        migrations.RemoveIndex(
            model_name='commissionrule',
            name='comm_rule_org_id_idx',
        ),
    ]
