# Generated by Django 5.2.7 on 2025-10-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('google_location', models.CharField(blank=True, max_length=255, null=True)),
                ('google_drive_link', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=50)),
                ('distance', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('available_start_date', models.DateField()),
                ('available_end_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='packages.city')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=20)),
                ('total_beds', models.IntegerField(default=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='tickets.hotels')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('room_type', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('is_sharing_allowed', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tickets.hotels')),
            ],
        ),
        migrations.CreateModel(
            name='HotelContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='tickets.hotels')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('is_assigned', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tickets.hotelrooms')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_meal_included', models.BooleanField(default=False)),
                ('is_refundable', models.BooleanField(default=False)),
                ('pnr', models.CharField(max_length=100)),
                ('child_price', models.FloatField(default=0)),
                ('infant_price', models.FloatField(default=0)),
                ('adult_price', models.FloatField(default=0)),
                ('total_seats', models.IntegerField(default=0)),
                ('left_seats', models.IntegerField(default=0)),
                ('booked_tickets', models.IntegerField(default=0)),
                ('confirmed_tickets', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('pieces', models.IntegerField(default=0)),
                ('is_umrah_seat', models.BooleanField(default=False)),
                ('trip_type', models.CharField(max_length=50)),
                ('departure_stay_type', models.CharField(max_length=50)),
                ('return_stay_type', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('inventory_owner_organization_id', models.IntegerField(blank=True, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='packages.airlines')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TickerStopoverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopover_duration', models.CharField(max_length=100)),
                ('trip_type', models.CharField(max_length=50)),
                ('stopover_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopover_tickets', to='packages.city')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopover_details', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date_time', models.DateTimeField()),
                ('arrival_date_time', models.DateTimeField()),
                ('trip_type', models.CharField(max_length=50)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_tickets', to='packages.city')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_tickets', to='packages.city')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_details', to='tickets.ticket')),
            ],
        ),
    ]
