# Generated by Django 5.2.7 on 2025-10-24 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 24, 10, 47, 33, 395788, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reselling_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 24, 10, 47, 33, 395754, tzinfo=datetime.timezone.utc)),
        ),
    ]
