# Generated by Django 5.2.7 on 2025-10-24 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_available_seats_ticket_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='left_seats',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 24, 10, 54, 29, 663069, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 24, 10, 54, 29, 663044, tzinfo=datetime.timezone.utc)),
        ),
    ]
