# Generated by Django 5.2.7 on 2025-10-24 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_left_seats_alter_ticket_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
