# Generated by Django 5.2.7 on 2025-10-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('tickets', '0004_alter_ticket_end_date_alter_ticket_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_ticket', to='organization.organization'),
        ),
    ]
